# Generated by Django 4.2.2 on 2024-04-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_alter_adduser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='adduser',
            name='User_types',
            field=models.CharField(default='admin', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adduser',
            name='Password',
            field=models.CharField(max_length=100),
        ),
    ]
